[package]
name = "telosom"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
colored = "*"
serde = { version = "1.0.203", features = ["derive"] } 
anyhow = "1.0.86"
